configs:
  N: 10000
  n_items: 400
  #hidden_layer_size: 5
  learning_rate: 0.05
  lr_warmup_epochs: 50
  lr_max_epochs: 1000
  lr_min: 0.0001
  single_epoch_test_run: False
  max_epochs: 1000
  min_epochs: 100
  min_delta: .0000008
  patience: 200
  batch_size: 10000
  which_data: 'gdina'
  save: False
  iteration : 1
  gumbel_temperature: 1
  gumbel_decay: .99
  gumbel_min_temp: .2